### ISSUE TITLE
GIF export freezes and shows handles

### ISSUE THREAD

**Issue by TristanBomb** [atomic-software/TISFAT-Zero#46]
GIF export frequently will freeze the program partway through rendering, and since GIF export appears to capture from the screen, that part of the GIF will be frozen as well. Sometimes, saving and re-opening will allow a work around, but it doesn't always work. It appears that the frame it freezes on is largely variable.

In addition, if you don't select the timeline before export, handles will be visible in the export.

**Comment by portify** [comment]
I believe handles being visible is because you can move the joints of the selected layer on keyframes, and thus it draws them for dragging. @Evar678 Should probably have a flag indicating that the program is exporting and not draw them if it's set instead of auto selecting timeline layer on export.
