### ISSUE TITLE
Error message upon changing light color

### ISSUE THREAD

**Issue by TristanBomb** [atomic-software/TISFAT-Zero#48]
I'm aware that changing light color is not an intended feature yet, and the button to visit object properties is grayed out while a light is selected. However, if a stick figure is selected first and then the object properties are visited, you can re-select the light and change the color. Doing so will result in the following unhandled exception:

System.InvalidCastException: Unable to cast object of type 'TISFAT_ZERO.LightFrame' to type 'TISFAT_ZERO.StickFrame'.

This error is non-fatal and you can continue using the program as normal afterwards.

**Comment by Evar678** [comment]
Hey, firstly thanks a ton for submitting this issue. Feel free to submit them as you encounter bugs

Secondly, huh, that's quite weird. Will get on it this weekend.
